import{A as v,S as y}from"./assets/vendor-0f055db0.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const r of s.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const b=[{question:"What programming languages are most often used in your project?",answer:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{question:"How can I contact you?",answer:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{question:"What are the deadlines for the project?",answer:"The terms of project implementation depend to a large extent on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines is a difficult task, and it usually occurs during the planning phase of the project."},{question:"Do you provide advice or support?",answer:"The terms of project implementation depend to a large extent on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines is a difficult task, and it usually occurs during the planning phase of the project."},{question:"What payment methods do you accept?",answer:"Payment through credit and debit cards such as Visa, MasterCard, specialized electronic payment systems such as PayPal, as well as payments in cryptocurrencies such as Bitcoin, Ethereum and others."},{question:"What does the process of developing a software product look like from idea to implementation?",answer:"Payment through credit and debit cards such as Visa, MasterCard, specialized electronic payment systems such as PayPal, as well as payments in cryptocurrencies such as Bitcoin, Ethereum and others."}];function q(e,n){const o=document.querySelector(n);let i="";e.forEach(t=>{const s=`
            <li class="faq-item">
                <h3 class="faq-item__header">
                    <button type="button" class="faq-item__btn">${t.question}</button>
                </h3>
                <div class="faq-item__content">
                    <div class="faq-item__content-inner">
                        <p>${t.answer}</p>
                    </div>
                </div>
            </li>
        `;i+=s}),o.innerHTML=i}q(b,".faq-list");new v(".faq-list",{duration:300,showMultiple:!0,elementClass:"faq-item",triggerClass:"faq-item__btn",panelClass:"faq-item__content"});const m=document.querySelector(".reviews-list"),p=document.querySelector(".rev-swiper-button-prev-js"),a=document.querySelector(".rev-swiper-button-next-js"),L="https://portfolio-js.b.goit.study/api/reviews",P={method:"GET",headers:{Accept:"application/json"}};let c=1,l=0,f=[];function j(){return fetch(L,P).then(e=>{if(!e.ok)throw new Error(`Network response was not ok ${e.status}`);return e.json()}).then(e=>{console.log("Reviews data:",e),f=e,w(),h()}).catch(e=>{console.error("Fetch error:",e)})}a.addEventListener("click",()=>g("next"));p.addEventListener("click",()=>g("prev"));function g(e){e==="next"?l++:l--,h()}function h(){const e=l*c,n=e+c,o=f.slice(e,n);m.innerHTML="",o.length===0?d(a):(m.innerHTML=o.map(({_id:i,author:t,avatar_url:s,review:r})=>`<li class="reviews-item rev-swiper-slide-js" id='${i}'>
            <img class="reviews-img" src="${s}" 
            alt="about-me" width="48" height="48" />
            <h3 class="reviews-name">${t}</h3>
            <p class="reviews-comment">${r}</p>
          </li>`).join(""),u(a)),l===0?d(p):u(p),n>=f.length?d(a):u(a)}function d(e){e.disabled=!0,e.classList.add("disabled")}function u(e){e.disabled=!1,e.classList.remove("disabled")}function w(){const e=window.innerWidth;e<768?c=1:e>=768&&e<1439?c=2:c=4}document.addEventListener("DOMContentLoaded",j);window.addEventListener("resize",()=>{w(),h()});new y(".swiper",{direction:"vertical",loop:!0,pagination:{el:".swiper-pagination"},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},scrollbar:{el:".swiper-scrollbar"}});
//# sourceMappingURL=commonHelpers.js.map
